name: wsa_pacman
description: A GUI package manager and package installer for Windows Subsystem for Android (WSA).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0 <3.3.10'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: 3.12.0
    #git: https://github.com/bdlukaa/fluent_ui.git
  shared_value: ^2.1.2
  synchronized: ^3.0.0
  provider: ^6.0.0
  system_theme: 2.0.0
  bitsdojo_window:
    git:
      # Credits to bufan22 for fixing errors with new Windows versions
      url: https://github.com/alesimula/bitsdojo_window.git
      path: bitsdojo_window
      ref: master
  smooth_scroll_multiplatform:
    git: https://github.com/alesimula/dyn_mouse_scroll.git
  flutter_acrylic: ^1.0.0+2
  url_strategy: ^0.2.0
  yaml: ^3.1.0
  #transparent_pointer: ^1.0.0
  archive: #3.1.11
    git: https://github.com/brendan-duncan/archive.git
  #flutter_svg: ^0.23.0+1
  jovial_svg:
    git: https://github.com/alesimula/jovial_svg.git
  protobuf: ^2.0.0
  #path_provider: ^2.0.6
  mdi: ^5.0.0-nullsafety.0
  win32: ^3.0.0
  base32: ^2.1.1
  charset: ^0.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_native_splash: ^2.0.1+1
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/missing_icon_background.si
    - assets/icons/missing_icon_foreground.si
    - assets/icons/missing_icon_legacy.si
    - assets/images/logo.png

#flutter_native_splash:
  #color: "#42a5f5"
  #image: web/assets/flutter_logo.png

